### ISSUE TITLE
Change colors

### ISSUE THREAD

**Issue by alextakitani** [lazaronixon/the_construct#6]
Hi, I'm struggling with the template for a few hours.

Do you know if there's a way to change it's colors?

Thanks!

**Comment by lazaronixon** [comment]
https://github.com/stisla/stisla you can change sass variable compile css and replace it in you project

**Comment by alextakitani** [comment]
I've ended up changing it on vendor/assets/stylesheets/stisla/style.css, it works fine. 

Thank you for your work on this project, its very good!
